server:
  port: 8085

spring:
    datasource:
        name: test
        url: jdbc:mysql://120.24.75.25:3306/b2b2c_db
        username: pqy
        password: pqy
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
     #关闭缓存
        cache: false
        request-context-attribute: request
        #模板加载的位置
        template-loader-path: classpath:/templates/
        suffix: .ftl
        check-template-location: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

debug: true

mybatis:
  mapper-locations: classpath*:**/*SqlMap.xml
  check-config-location: true
